name: Build Android APK Auto Path

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Robot akan mencari otomatis di mana folder yang berisi file gradlew
      - name: Build APK Debug
        run: |
          GRADLEW_PATH=$(find . -name gradlew -print -quit)
          GRADLEW_DIR=$(dirname "$GRADLEW_PATH")
          echo "File gradlew ditemukan di folder: $GRADLEW_DIR"
          cd "$GRADLEW_DIR"
          chmod +x gradlew
          ./gradlew assembleDebug

      # Robot akan mencari otomatis di mana hasil file APK-nya berada
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aplikasi-Android-Kamu
          path: "**/build/outputs/apk/debug/app-debug.apk"
